name: flutter_bluetooth_basic_v2_example
description: Demonstrates how to use the flutter_bluetooth_basic_v2 plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.1'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^1.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_basic_v2:
    path: ../

flutter:
  uses-material-design: true
