name: flutter_bluetooth_basic_v2
description: Flutter plugin that allows to find bluetooth devices & send raw 
  bytes data (v2)
version: 0.0.5
homepage: https://github.com/oengoengmengthong/flutter_bluetooth_basic_v2

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  rxdart: ^0.26.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  plugin:
    platforms:
      android:
        package: com.oengmengthong.flutter_bluetooth_basic_v2
        pluginClass: FlutterBluetoothBasicV2Plugin
      ios:
        pluginClass: FlutterBluetoothBasicV2Plugin
